import React from 'react';
import {
  A, Bold, Char,
  Code, Details,
  Dl,
  Em,
  Gray,
  H,
  Image, Kbd,
  Line, Mark, Message, NoteBottom, NoteTop,
  Ol,
  P,
  Prism, Q, Quote,
  Score, Spoiler,
  Strike,
  Strong,
  Ul, Youtube, HtmlGuideMessage, Name
} from '@/components/PostComponents';

interface Props {
  [x: string]: string;
}

export const MDXComponents = {
  h1: (props: Props) => <H type='1' {...props} />,
  h2: (props: Props) => <H type='2' {...props} />,
  h3: (props: Props) => <H type='3' {...props} />,
  h4: (props: Props) => <H type='4' {...props} />,
  inlineCode: (props: Props) => <Code {...props} />,
  p: (props: Props) => <P {...props} />,
  img: (props: Props) => <Image {...props} />,
  a: (props: Props) => <A {...props} />,
  del: (props: Props) => <Strike {...props} />,
  strong: (props: Props) => <Strong {...props} />,
  em: (props: Props) => <Em {...props} />,
  ol: (props: Props) => <Ol {...props} />,
  ul: (props: Props) => <Ul {...props} />,
  pre: (props: Props) => <Prism {...props} />,
  hr: (props: Props) => <Line {...props} />,
  H,
  Code,
  A,
  P,
  Image,
  Strong,
  Strike,
  Em,
  Ol,
  Ul,
  Dl,
  Score,
  Gray,
  Details,
  Bold,
  Kbd,
  Char,
  Message,
  NoteTop,
  NoteBottom,
  Q,
  Quote,
  Spoiler,
  Youtube,
  Mark,
  Line,
  HtmlGuideMessage,
  Name,
};
